# python exploratory data analysis
* data understanding
* data cleaning
* data analysis
* data preprocessing (feature engineering)

In [1]:
#!pip install pandas

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("cricinfo.csv")

In [4]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [5]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Player  62 non-null     str
 1   Span    62 non-null     str
 2   Mat     62 non-null     int64
 3   Inns    62 non-null     int64
 4   NO      62 non-null     int64
 5   Runs    62 non-null     int64
 6   HS      62 non-null     str
 7   Ave     62 non-null     float64
 8   BF      62 non-null     str
 9   SR      62 non-null     str
 10  100     62 non-null     int64
 11  50      62 non-null     int64
 12  0       62 non-null     str
 13  4s      62 non-null     int64
 14  6s      62 non-null     int64
dtypes: float64(1), int64(8), str(6)
memory usage: 9.8 KB

In [7]:
df

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [8]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1

In [9]:
df.tail()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [10]:
df.sample(5)

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
17,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,55.37,28903,45.97,45,58,16,1488,97
56,RN Harvey (AUS),1948-1963,79,137,10,6149,205,48.41,1799+,43.74,21,24,7,427,1
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,60.73,6558+,34.59,16,23,2,202,6
47,FMM Worrell (WI),1948-1963,51,87,9,3860,261,49.48,488+,40.16,9,22,11,240,11
25,BC Lara (ICC/WI),1990-2006,131,232,6,11953,400*,52.88,19753,60.51,34,48,17,1559,88

In [11]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [12]:
df.rename(columns={'Mat':'Matches'})

,Player,Span,Matches,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [13]:
df.columns

Index(['Player', 'Span', 'Mat', 'Inns', 'NO', 'Runs', 'HS', 'Ave', 'BF', 'SR',
       '100', '50', '0', '4s', '6s'],
      dtype='str')

In [14]:
df.rename(columns={'HS':'Highest_score','Ave':'Average','SR':'Strike_rate','BF':'Balls_faced'},inplace=True)

In [15]:
df

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0

In [16]:
df['country']=df['Player'].str.split(pat='(').str[1]

In [17]:
df

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS)
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL)
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS)
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA)
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS)
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA)
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS)
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS)
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG)

In [18]:
df['country']=df['country'].str.split(pat=")").str[0]

In [19]:
df

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182*,62.31,1839,64.38,5,4,-,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Mat            62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     str
 7   Average        62 non-null     float64
 8   Balls_faced    62 non-null     str
 9   Strike_rate    62 non-null     str
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     str
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(8), object(1), str(6)
memory usage: 10.3+ KB

In [21]:
df.Highest_score

0      334
1     182*
2     269*
3      274
4     270*
      ...
57     250
58     277
59     266
60     232
61     127
Name: Highest_score, Length: 62, dtype: str

In [22]:
df['Highest_score'].str.split(pat='*').str[0]

0     334
1     182
2     269
3     274
4     270
     ...
57    250
58    277
59    266
60    232
61    127
Name: Highest_score, Length: 62, dtype: object

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Mat            62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     str
 7   Average        62 non-null     float64
 8   Balls_faced    62 non-null     str
 9   Strike_rate    62 non-null     str
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     str
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(8), object(1), str(6)
memory usage: 10.3+ KB

In [24]:
df['Highest_score']

0      334
1     182*
2     269*
3      274
4     270*
      ...
57     250
58     277
59     266
60     232
61     127
Name: Highest_score, Length: 62, dtype: str

In [25]:
df['Highest_score']=df['Highest_score'].str.split(pat="*").str[0]

In [26]:
df['Highest_score']=df['Highest_score'].astype(int)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Mat            62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    62 non-null     str
 9   Strike_rate    62 non-null     str
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     str
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(1), int64(9), object(1), str(5)
memory usage: 10.1+ KB

In [28]:
df[df["Strike_rate"]=="-"]

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
8,ED Weekes (WI),1948-1958,48,81,5,4455,207,58.61,-,-,15,19,6,258,2,WI
15,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107,11,WI
54,Hon.FS Jackson (ENG),1893-1905,20,33,4,1415,144,48.79,-,-,5,6,3,51,0,ENG

In [29]:
df["Strike_rate"]=df["Strike_rate"].replace("-",0)

In [30]:
df["Balls_faced"]=df["Balls_faced"].replace("-",0)

In [31]:
df["0"]=df["0"].replace("-",0)

In [32]:
df

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416+,56,10,5,2,104,1,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),1965-1981,74,125,14,5357,250,48.26,8662+,49.16,15,33,4,525,23,AUS
58,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,ICC/SA
59,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119,0,AUS
60,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241,5,AUS
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53,0,ENG

In [33]:
df["Balls_faced"]=df["Balls_faced"].str.split(pat="+").str[0]

In [34]:
df["Balls_faced"]=df["Balls_faced"].astype(float)

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Mat            62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    59 non-null     float64
 9   Strike_rate    62 non-null     object
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     object
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(2), int64(9), object(3), str(2)
memory usage: 9.4+ KB

In [36]:
df["Strike_rate"]=df["Strike_rate"].astype(float)

In [37]:
df["0"]=df["0"].astype(int)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         62 non-null     str
 1   Span           62 non-null     str
 2   Mat            62 non-null     int64
 3   Inns           62 non-null     int64
 4   NO             62 non-null     int64
 5   Runs           62 non-null     int64
 6   Highest_score  62 non-null     int64
 7   Average        62 non-null     float64
 8   Balls_faced    59 non-null     float64
 9   Strike_rate    62 non-null     float64
 10  100            62 non-null     int64
 11  50             62 non-null     int64
 12  0              62 non-null     int64
 13  4s             62 non-null     int64
 14  6s             62 non-null     int64
 15  country        62 non-null     object
dtypes: float64(3), int64(10), object(1), str(2)
memory usage: 9.4+ KB

In [39]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS
1,PHKD Mendis (SL),2022-2025,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL
2,AC Voges (AUS),2015-2016,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA
4,GA Headley (WI),1930-1954,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI

In [40]:
df["Start_year"]=df["Span"].str.split(pat="-").str[0].astype(int)

In [41]:
df["end_year"]=df["Span"].str.split(pat="-").str[1].astype(int)

In [42]:
df["Span"]=df["end_year"]-df["Start_year"]

In [44]:
df2=df

In [ ]:
df2["Duration"]=df2["start_year"]-df2["end_year"]

In [45]:
df1=pd.read_csv("cricinfo.csv")

In [46]:
df1["Span"]

0     1928-1948
1     2022-2025
2     2015-2016
3     1963-1970
4     1930-1954
        ...
57    1965-1981
58    2002-2014
59    1924-1934
60    1930-1938
61    1928-1934
Name: Span, Length: 62, dtype: str

In [48]:
df2

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country,Start_year,end_year
0,DG Bradman (AUS),20,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis (SL),3,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL,2022,2025
2,AC Voges (AUS),1,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock (SA),7,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley (WI),24,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),16,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,525,23,AUS,1965,1981
58,GC Smith (ICC/SA),12,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,1165,24,ICC/SA,2002,2014
59,WH Ponsford (AUS),10,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,119,0,AUS,1924,1934
60,SJ McCabe (AUS),8,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,241,5,AUS,1930,1938
61,DR Jardine (ENG),6,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,53,0,ENG,1928,1934

In [ ]:
df2["span"] = df1["span"]

In [52]:
df2.rename(columns={"span":"Duration(year)"},inplace=True)

In [51]:
df2

,Player,Span,Mat,Inns,NO,Runs,Highest_score,Average,Balls_faced,Strike_rate,100,50,0,4s,6s,country,Start_year,end_year
0,DG Bradman (AUS),20,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,AUS,1928,1948
1,PHKD Mendis (SL),3,12,21,2,1184,182,62.31,1839.0,64.38,5,4,0,123,23,SL,2022,2025
2,AC Voges (AUS),1,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,AUS,2015,2016
3,RG Pollock (SA),7,23,41,4,2256,274,60.97,1707.0,54.48,7,11,1,246,11,SA,1963,1970
4,GA Headley (WI),24,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,WI,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,KD Walters (AUS),16,74,125,14,5357,250,48.26,8662.0,49.16,15,33,4,525,23,AUS,1965,1981
58,GC Smith (ICC/SA),12,117,205,13,9265,277,48.25,15525.0,59.67,27,38,11,1165,24,ICC/SA,2002,2014
59,WH Ponsford (AUS),10,29,48,4,2122,266,48.22,3118.0,44.77,7,6,1,119,0,AUS,1924,1934
60,SJ McCabe (AUS),8,39,62,5,2748,232,48.21,3217.0,60.02,6,13,4,241,5,AUS,1930,1938
61,DR Jardine (ENG),6,22,33,6,1296,127,48.00,2110.0,25.59,1,10,2,53,0,ENG,1928,1934

In [53]:
df.to_csv("cleanedfile.csv")